### ISSUE TITLE
May meetup

### ISSUE THREAD

**Issue by betatim** [pydatazrh/meetup#21]
When: first half of May
Where: TBD

Format: three times 20min talks about ...

* ... basic tools (pandas, jupyter and X??)
* ... (deep) learning with python
* ... different topic?

If we can arrange for three talks on a similar topic that would be great.

**Comment by betatim** [comment]
cc @jakeret

**Comment by gianba** [comment]
Hi, I'm a data scientist at Zühlke. If desired I could talk about how we setup analytics pipelines in data science projects. The talk would focus on how we employ Jupyter notebooks and regular python functions and classes to achieve reproducability, testability and allow for an operationalization of the models.
Any news on what date the event will take place?

cheers,
Gian-Marco

**Comment by betatim** [comment]
Sounds interesting. So should we collect some talks on the topic of notebooks then?

Date is going to be tricky I think ... at least for me as Ill actually be at PyCon for a large part of May ...

**Comment by jakeret** [comment]
Since there is no much time left till PyCon and I'm gone as well later this month, should we try to settle on a date? I propose **Tuesday 16th of May**.
I guess It's going to be hard, to find more talks on this particular topic. @betatim could you give a talk on Bayesion Optimiztation?

**Comment by betatim** [comment]
I could talk about Bayesian optimisation all day long, but not by 16 May. Work and preparing for PyCon has taken over my life :(

**Comment by jakeret** [comment]
Should we rename this issue and give it another try in june? ;-)

**Comment by betatim** [comment]
👍

**Comment by betatim** [comment]
-> #23
