### ISSUE TITLE
September meetup

### ISSUE THREAD

**Issue by jakeret** [pydatazrh/meetup#27]
Let's try to schedule a meetup towards the end of september:

- @markusbaden Modern pension fund analytics using pandas, jupyter and dask
- another awesome speaker

### Date
- xx.09.2017

### Location
- TDB

**Comment by wolfv** [comment]
I'd be happy to talk about `xtensor` / `xtensor-python` but I only have time at the beginning of October.

https://github.com/QuantStack/xtensor
https://github.com/QuantStack/xtensor-python

**Comment by betatim** [comment]
That would be exciting @wolfv, created a new issue #28 to keep the discussions nice and tidy.

**Comment by markusbaden** [comment]
the last week of September is not possible for me, so it's either Sep 18 to 22 or Oct 2 to 6.

**Comment by wolfv** [comment]
If it would be Oct 2 - 6 it would actually also work well for me... if you would consider this :) Otherwise, also happy to come back at the end of Oct.

**Comment by jakeret** [comment]
How about we merge the two meetups, say for Thursday the 5th of October?

**Comment by jakeret** [comment]
@markusbaden I moved your talk to the october meetup and set the date for the 5th of October.

This means that there is not going to be a September meetup

**Comment by markusbaden** [comment]
perfect, let's continue the discussion in #28
