### ISSUE TITLE
Blockchain todos

### ISSUE THREAD

**Issue by jakeret** [pydatazrh/meetup#37]
Todo @kmader @betatim @markusbaden @Sebubu 

- [x] GitHub permission for jakeret
  - [x] move repo to pydatazrh

- [x] Slide to thank host

- [x] Slide with Links to Survey and GitHub
- [ ] Encourage people to press watch button

- [x] Slide for SPS promotion

- [x] Slide for recap after apero

- [ ] Slide for consensus

**Comment by betatim** [comment]
https://camo.githubusercontent.com/5158e67c2323263463923effbbda29cda46e7a6c/68747470733a2f2f68656c702e6769746875622e636f6d2f6173736574732f696d616765732f68656c702f6e6f74696669636174696f6e732f776174636865725f7069636b65722e676966

link to a GIF showing how to use the watch button

**Comment by betatim** [comment]
(added a "move repo to pydatazrh" todo)

**Comment by markusbaden** [comment]
Which is the repo to use for the binder ready notebooks? This one https://github.com/jakeret/blockchain_pydatazrh?

**Comment by jakeret** [comment]
Nope I just moved everything to: https://github.com/pydatazrh/blockchain_pydatazrh

**Comment by betatim** [comment]
And I renamed it to https://github.com/pydatazrh/christmas_special_2017 (but the old link still works)

**Comment by betatim** [comment]
Feel free to re-open.
