### ISSUE TITLE
Are these the full slides to the talk?

### ISSUE THREAD

**Issue by ucg8j** [pydatazrh/meetup#39]
https://github.com/pydatazrh/meetup/blob/master/Meetup8/Dash_Talk.pdf

Fascinating talk as a shiny and dash user, but I suspect these slides are truncated. Is it possible to get a full upload?

**Comment by betatim** [comment]
I think the rest was live demo'ing, check out https://github.com/pydatazrh/meetup/tree/master/Meetup8#dash-info

**Comment by ucg8j** [comment]
Ah cool, thanks @betatim and thanks to @kmader for sharing them.

**Comment by betatim** [comment]
Closing for now. Feel free to reopen.
